# Generated by Django 4.1 on 2022-09-29 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_order_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carts',
            old_name='Product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Product_name',
            new_name='product',
        ),
    ]
